package com.google.android.gms.internal.gtm;

import ch.qos.logback.classic.Level;
import ch.qos.logback.core.CoreConstants;
import ch.qos.logback.core.spi.AbstractComponentTracker;
import ch.qos.logback.core.spi.ComponentTracker;
import com.google.android.gms.auth.api.credentials.CredentialsApi;
import com.google.android.gms.common.internal.ShowFirstParty;
import com.google.android.gms.common.util.VisibleForTesting;
import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import org.joda.time.DateTimeConstants;
@ShowFirstParty
@VisibleForTesting
/* loaded from: classes5.dex */
public final class zzeu {
    public static final zzet<Integer> zzA;
    public static final zzet<String> zzB;
    public static final zzet<Integer> zzC;
    public static final zzet<Long> zzD;
    public static final zzet<Integer> zzE;
    public static final zzet<Integer> zzF;
    public static final zzet<Long> zzG;
    public static final zzet<String> zzH;
    public static final zzet<Integer> zzI;
    public static final zzet<Boolean> zzJ;
    public static final zzet<Long> zzK;
    public static final zzet<Long> zzL;
    public static final zzet<Long> zzM;
    public static final zzet<Long> zzN;
    public static final zzet<Long> zzO;
    public static final zzet<Long> zzP;
    public static final zzet<Long> zzQ;
    public static final zzet<Boolean> zzR;
    private static final Set<zzet<?>> zzS = Collections.synchronizedSet(new HashSet());
    public static final zzet<Boolean> zza;
    public static final zzet<Boolean> zzb;
    public static final zzet<String> zzc;
    public static final zzet<Long> zzd;
    public static final zzet<Double> zze;
    public static final zzet<Integer> zzf;
    public static final zzet<Integer> zzg;
    public static final zzet<Integer> zzh;
    public static final zzet<Long> zzi;
    public static final zzet<Long> zzj;
    public static final zzet<Long> zzk;
    public static final zzet<Long> zzl;
    public static final zzet<Long> zzm;
    public static final zzet<Long> zzn;
    public static final zzet<Integer> zzo;
    public static final zzet<Integer> zzp;
    public static final zzet<String> zzq;
    public static final zzet<String> zzr;
    public static final zzet<String> zzs;
    public static final zzet<String> zzt;
    public static final zzet<Integer> zzu;
    public static final zzet<String> zzv;
    public static final zzet<String> zzw;
    public static final zzet<Integer> zzx;
    public static final zzet<Integer> zzy;
    public static final zzet<Integer> zzz;

    static {
        Boolean bool = Boolean.FALSE;
        zza = zzet.zza(bool, bool, zzda.zza);
        Boolean bool2 = Boolean.TRUE;
        zzb = zzet.zza(bool2, bool2, zzdl.zza);
        zzc = zzet.zza("GAv4", "GAv4-SVC", zzdd.zza);
        zzd = zzet.zza(60L, 60L, zzdp.zza);
        Double valueOf = Double.valueOf(0.5d);
        zze = zzet.zza(valueOf, valueOf, zzeb.zza);
        Integer valueOf2 = Integer.valueOf((int) CredentialsApi.CREDENTIAL_PICKER_REQUEST_CODE);
        zzf = zzet.zza(valueOf2, Integer.valueOf((int) Level.INFO_INT), zzeg.zza);
        zzg = zzet.zza(valueOf2, valueOf2, zzei.zza);
        zzh = zzet.zza(100, 100, zzej.zza);
        Long valueOf3 = Long.valueOf((long) ComponentTracker.DEFAULT_TIMEOUT);
        zzi = zzet.zza(valueOf3, 120000L, zzek.zza);
        zzj = zzet.zza(5000L, 5000L, zzel.zza);
        zzk = zzet.zza(120000L, 120000L, zzdw.zza);
        zzl = zzet.zza(7200000L, 7200000L, zzeh.zza);
        zzm = zzet.zza(7200000L, 7200000L, zzem.zza);
        zzn = zzet.zza(32400000L, 32400000L, zzen.zza);
        zzo = zzet.zza(20, 20, zzeo.zza);
        zzp = zzet.zza(20, 20, zzep.zza);
        zzq = zzet.zza("http://www.google-analytics.com", "http://www.google-analytics.com", zzeq.zza);
        zzr = zzet.zza("https://ssl.google-analytics.com", "https://ssl.google-analytics.com", zzer.zza);
        zzs = zzet.zza("/collect", "/collect", zzdb.zza);
        zzt = zzet.zza("/batch", "/batch", zzdc.zza);
        zzu = zzet.zza(2036, 2036, zzde.zza);
        zzv = zzet.zza("BATCH_BY_COUNT", "BATCH_BY_COUNT", zzdf.zza);
        zzw = zzet.zza("GZIP", "GZIP", zzdg.zza);
        zzx = zzet.zza(20, 20, zzdh.zza);
        zzy = zzet.zza(8192, 8192, zzdi.zza);
        zzz = zzet.zza(8192, 8192, zzdj.zza);
        zzA = zzet.zza(8192, 8192, zzdk.zza);
        zzB = zzet.zza("404,502", "404,502", zzdm.zza);
        zzC = zzet.zza(3600, 3600, zzdn.zza);
        Long valueOf4 = Long.valueOf((long) CoreConstants.MILLIS_IN_ONE_DAY);
        zzD = zzet.zza(valueOf4, valueOf4, zzdo.zza);
        Integer valueOf5 = Integer.valueOf((int) DateTimeConstants.MILLIS_PER_MINUTE);
        zzE = zzet.zza(valueOf5, valueOf5, zzdq.zza);
        zzF = zzet.zza(61000, 61000, zzdr.zza);
        zzG = zzet.zza(valueOf4, valueOf4, zzds.zza);
        zzH = zzet.zza("", "", zzdt.zza);
        zzI = zzet.zza(0, 0, zzdu.zza);
        zzJ = zzet.zza(bool, bool, zzdv.zza);
        Long valueOf6 = Long.valueOf((long) AbstractComponentTracker.LINGERING_TIMEOUT);
        zzK = zzet.zza(valueOf6, valueOf6, zzdx.zza);
        zzL = zzet.zza(5000L, 5000L, zzdy.zza);
        zzM = zzet.zza(5000L, 5000L, zzdz.zza);
        zzN = zzet.zza(60000L, 60000L, zzea.zza);
        zzO = zzet.zza(valueOf3, valueOf3, zzec.zza);
        zzP = zzet.zza(valueOf4, valueOf4, zzed.zza);
        zzQ = zzet.zza(5000L, 5000L, zzee.zza);
        zzR = zzet.zza(bool, bool, zzef.zza);
    }
}
