package p000;

import kotlin.Metadata;
import kotlin.NotImplementedError;
@Metadata(m28433d1 = {"\u0000\f\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0000\n\u0000\bf\u0018\u0000*\u0004\b\u0000\u0010\u00012\u00020\u0002¨\u0006\u0003"}, m28432d2 = {"LRE3;", "T", "", "parcelize-runtime"}, m28431k = 1, m28430mv = {1, 8, 0})
/* renamed from: RE3 */
/* loaded from: classes8.dex */
public interface RE3<T> {

    @Metadata(m28431k = 3, m28430mv = {1, 8, 0}, m28428xi = 48)
    /* renamed from: RE3$a */
    /* loaded from: classes8.dex */
    public static final class C7102a {
        /* renamed from: a */
        public static <T> T[] m87008a(RE3<T> re3, int i) {
            throw new NotImplementedError("Generated by Android Extensions automatically");
        }
    }
}
